"use server";

import { auth } from "@/auth";
import {
  CategoryTable,
  CountryTable,
  CurrencyTable,
  db,
  productVariantOptionTable,
  productVariantOptionValueTable,
} from "@/db";
import iconv from "iconv-lite";
import Countries from "./country.json";
import Currencies from "./currency.json";

const sanitize = (str: string) => iconv.decode(iconv.encode(str, "utf8"), "utf8");

export async function seedCountries() {
  const session = await auth();

  if (!session?.user?.roles?.includes("admin")) {
    throw new Error("Unauthorized");
  }

  const res = await db
    .insert(CountryTable)
    .values(
      Countries.map((item) => ({
        displayName: sanitize(item.display_name),
        name: sanitize(item.name),
        updatedBy: session.user.id,
      })),
    )
    .returning({ id: CountryTable.id });
  return { countriesCreated: res.length };
}
export async function seedCurrencies() {
  const session = await auth();
  if (!session?.user?.roles.includes("admin")) {
    throw new Error("Unauthorized");
  }

  const res = await db
    .insert(CurrencyTable)
    .values(
      Currencies.map((item) => ({
        symbol: sanitize(item.symbol),
        name: sanitize(item.name),
        updatedBy: session.user.id,
        code: item.code,
        isDefault: item.code === "usd",
        isAvailable: false,
      })),
    )
    .returning({ id: CurrencyTable.id });
  return { currenciesCreated: res.length };
}

export async function seedOptions() {
  const session = await auth();
  if (!session?.user?.roles.includes("admin")) {
    throw new Error("Unauthorized");
  }
  const res = await db.transaction(async (trx) => {
    const optionsSeed = [
      {
        name: "size",
        values: [
          { name: "extra small", metaData: { code: "XS" } },
          { name: "small", metaData: { code: "S" } },
          { name: "medium", metaData: { code: "M" } },
          { name: "large", metaData: { code: "L" } },
          { name: "extra large", metaData: { code: "XL" } },
          { name: "extra extra large", metaData: { code: "XXL" } },
        ],
      },
      {
        name: "color",
        values: [
          { name: "black", metaData: { hex: "#000000" } },
          { name: "white", metaData: { hex: "#FFFFFF" } },
          { name: "navy", metaData: { hex: "#000080" } },
          { name: "gray", metaData: { hex: "#808080" } },
          { name: "red", metaData: { hex: "#FF0000" } },
          { name: "blue", metaData: { hex: "#0000FF" } },
          { name: "green", metaData: { hex: "#008000" } },
          { name: "yellow", metaData: { hex: "#FFFF00" } },
        ],
      },
    ];
    const options = await trx
      .insert(productVariantOptionTable)
      .values(
        optionsSeed.map((item) => ({
          name: item.name,
          updatedBy: session.user.id,
        })),
      )
      .returning();

    const res = await Promise.all(
      options.map((option) => {
        const values = optionsSeed.find((item) => item.name === option.name)?.values ?? [];
        return trx.insert(productVariantOptionValueTable).values(
          values.map((value) => ({
            optionId: option.id,
            name: value.name,
            metaData: value.metaData,
          })),
        );
      }),
    );
  });

  return { optionsCreated: 13 };
}
export const seedCategories = async () => {
  const session = await auth();
  if (!session?.user?.roles.includes("admin")) {
    throw new Error("Unauthorized");
  }
  const categoryData = [
    {
      id: "pcat_01HE0T85S7B7G5Y2GN0TSG5B6M",
      created_at: "2023-10-30T17:31:36.611Z",
      updated_at: "2024-07-16T11:06:47.609Z",
      name: "APPAREL",
      description: "",
      handle: "Apparel",
      is_active: true,
      is_internal: false,
      parent_category_id: null,
      rank: 0,
      metadata: null,
      category_children: [
        {
          id: "pcat_01HE0TH2V73Q0WEHESA20BZFB3",
          created_at: "2023-10-30T17:36:28.511Z",
          updated_at: "2024-07-16T11:06:47.609Z",
          name: "Dress",
          description: "",
          handle: "Dress",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0T85S7B7G5Y2GN0TSG5B6M",
          rank: 0,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBKC2RDER62E9X740JZ687B",
          created_at: "2023-11-28T18:34:26.948Z",
          updated_at: "2024-07-16T11:06:47.609Z",
          name: "Tops",
          description: "",
          handle: "Tops",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0T85S7B7G5Y2GN0TSG5B6M",
          rank: 1,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBKCPZT7FPX072YHT2CRQ01",
          created_at: "2023-11-28T18:34:47.667Z",
          updated_at: "2024-07-16T11:06:47.609Z",
          name: "Tunic/Kaftan",
          description: "",
          handle: "Tunic-Kaftan",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0T85S7B7G5Y2GN0TSG5B6M",
          rank: 2,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBKDVXJ5BCQ3MK15N0ZY1KQ",
          created_at: "2023-11-28T18:35:25.482Z",
          updated_at: "2024-07-16T11:06:47.609Z",
          name: "Skirt",
          description: "",
          handle: "Skirt",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0T85S7B7G5Y2GN0TSG5B6M",
          rank: 3,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBKF9YJK7Z02M8PEZTE9CAD",
          created_at: "2023-11-28T18:36:12.620Z",
          updated_at: "2024-07-16T11:06:47.609Z",
          name: "Cape/Kimono",
          description: "",
          handle: "Cape-kimono",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0T85S7B7G5Y2GN0TSG5B6M",
          rank: 4,
          metadata: null,
          category_children: [
            {
              id: "pcat_01HGBKRYWSRRNSMC75KJ368ZT6",
              created_at: "2023-11-28T18:41:28.979Z",
              updated_at: "2024-07-16T11:06:47.609Z",
              name: "Hair Accessories",
              description: "",
              handle: "Hair-Accessories",
              is_active: true,
              is_internal: false,
              parent_category_id: "pcat_01HGBKF9YJK7Z02M8PEZTE9CAD",
              rank: 0,
              metadata: null,
              category_children: [],
            },
          ],
        },
        {
          id: "pcat_01HMXEQ42AN6XJ6T3XFW48F5T9",
          created_at: "2024-01-24T10:02:12.929Z",
          updated_at: "2024-07-16T11:06:47.609Z",
          name: "Pants",
          description: "",
          handle: "pants",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0T85S7B7G5Y2GN0TSG5B6M",
          rank: 5,
          metadata: null,
          category_children: [],
        },
      ],
      parent_category: null,
    },
    {
      id: "pcat_01HE0T9D5WAYFD4MQ1SMR5AWH5",
      created_at: "2023-10-30T17:32:16.952Z",
      updated_at: "2024-07-16T11:06:47.609Z",
      name: "ACCESSORIES",
      description: "",
      handle: "Accessories",
      is_active: true,
      is_internal: false,
      parent_category_id: null,
      rank: 1,
      metadata: null,
      category_children: [
        {
          id: "pcat_01HE0TP8MGP009GAWY30DR4211",
          created_at: "2023-10-30T17:39:18.280Z",
          updated_at: "2024-07-16T11:06:47.609Z",
          name: "Scarves & Wraps",
          description: "",
          handle: "Scarves and Wraps",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0T9D5WAYFD4MQ1SMR5AWH5",
          rank: 0,
          metadata: null,
          category_children: [
            {
              id: "pcat_01J88304YWN1EN7JWS8D3H80BQ",
              created_at: "2024-09-20T16:07:19.249Z",
              updated_at: "2024-09-20T16:07:19.249Z",
              name: "Autumn and Winter Scarves ",
              description: "",
              handle: "autumn-and-winter-scarves",
              is_active: true,
              is_internal: false,
              parent_category_id: "pcat_01HE0TP8MGP009GAWY30DR4211",
              rank: 0,
              metadata: {},
              category_children: [
                {
                  id: "pcat_01J88313286S1ZDTRWDQ4B2GGB",
                  created_at: "2024-09-20T16:07:50.078Z",
                  updated_at: "2024-09-20T16:07:50.078Z",
                  name: "Plain Cashmere Scarves",
                  description: "",
                  handle: "plain-cashmere-scarves",
                  is_active: true,
                  is_internal: false,
                  parent_category_id: "pcat_01J88304YWN1EN7JWS8D3H80BQ",
                  rank: 0,
                  metadata: {},
                  category_children: [],
                },
              ],
            },
          ],
        },
        {
          id: "pcat_01HGBKNWFVXAFQ7CYJHXJE07PW",
          created_at: "2023-11-28T18:39:48.212Z",
          updated_at: "2024-07-16T11:06:47.609Z",
          name: "Belt",
          description: "",
          handle: "Belt",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0T9D5WAYFD4MQ1SMR5AWH5",
          rank: 1,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBKPG6ZDEQP4M7NP9BDYE4J",
          created_at: "2023-11-28T18:40:08.409Z",
          updated_at: "2024-07-16T11:06:47.609Z",
          name: "Hats",
          description: "",
          handle: "Hats",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0T9D5WAYFD4MQ1SMR5AWH5",
          rank: 2,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBKQCV0K4J3DJ1S05YYJ5PQ",
          created_at: "2023-11-28T18:40:37.722Z",
          updated_at: "2024-07-16T11:06:47.609Z",
          name: "Gloves",
          description: "",
          handle: "Gloves",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0T9D5WAYFD4MQ1SMR5AWH5",
          rank: 3,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBKR4HKF3RHRA41E8EVMZ7C",
          created_at: "2023-11-28T18:41:01.996Z",
          updated_at: "2024-07-16T11:06:47.609Z",
          name: "Socks",
          description: "",
          handle: "Socks",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0T9D5WAYFD4MQ1SMR5AWH5",
          rank: 4,
          metadata: null,
          category_children: [],
        },
      ],
      parent_category: null,
    },
    {
      id: "pcat_01HE0TANP61JCNEBETKHJV2CPV",
      created_at: "2023-10-30T17:32:58.434Z",
      updated_at: "2024-07-16T11:07:04.283Z",
      name: "HANDBAGS",
      description: "",
      handle: "Handbags",
      is_active: true,
      is_internal: false,
      parent_category_id: null,
      rank: 2,
      metadata: null,
      category_children: [
        {
          id: "pcat_01HE0TRD300NS734Z4RKM6GWSW",
          created_at: "2023-10-30T17:40:28.376Z",
          updated_at: "2024-07-16T11:07:04.283Z",
          name: "Totes & Carryalls",
          description: "",
          handle: "Totes-Carryalls",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TANP61JCNEBETKHJV2CPV",
          rank: 0,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBFQZVYB74QNA0JNTA4EFAQ",
          created_at: "2023-11-28T17:31:02.895Z",
          updated_at: "2024-07-16T11:07:04.283Z",
          name: "Handbags & Purses",
          description: "",
          handle: "Handbags-Purses",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TANP61JCNEBETKHJV2CPV",
          rank: 1,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBM5FRSPGEMKYJM1A90BGWK",
          created_at: "2023-11-28T18:48:19.475Z",
          updated_at: "2024-07-16T11:07:04.283Z",
          name: "Pouches & Clutches",
          description: "",
          handle: "Pouches-Clutches",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TANP61JCNEBETKHJV2CPV",
          rank: 2,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBM6NE2YD92F8RDESJNKK89",
          created_at: "2023-11-28T18:48:58.044Z",
          updated_at: "2024-07-16T11:07:04.283Z",
          name: "Hands Free Bags",
          description: "",
          handle: "Hands-Free-Bags",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TANP61JCNEBETKHJV2CPV",
          rank: 3,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGMR4MYEG01PRC5K1TV126DM",
          created_at: "2023-12-02T07:50:56.196Z",
          updated_at: "2024-07-16T11:07:04.283Z",
          name: "Budget Tote",
          description: "",
          handle: "Budget-tote",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TANP61JCNEBETKHJV2CPV",
          rank: 4,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01J52RVK7DY1TXT2RABEA3TCVB",
          created_at: "2024-08-12T07:46:46.625Z",
          updated_at: "2024-08-12T07:46:46.625Z",
          name: "Canvas Handbag",
          description: "CSBG3082 Floral",
          handle: "Handle Drop",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TANP61JCNEBETKHJV2CPV",
          rank: 5,
          metadata: {},
          category_children: [],
        },
        {
          id: "pcat_01J52S33JW9RZM4TZYS2T95GSE",
          created_at: "2024-08-12T07:50:52.756Z",
          updated_at: "2024-08-12T07:50:52.756Z",
          name: "FLORAL HANDBAG",
          description: "PRINTED HEAVY CANVAS.",
          handle: "floral-handbag",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TANP61JCNEBETKHJV2CPV",
          rank: 6,
          metadata: {},
          category_children: [],
        },
      ],
      parent_category: null,
    },
    {
      id: "pcat_01HE0TBF57CC2CP81R4A48TEY8",
      created_at: "2023-10-30T17:33:24.515Z",
      updated_at: "2024-07-16T11:07:18.505Z",
      name: "JEWELRY",
      description: "",
      handle: "Jewelry",
      is_active: true,
      is_internal: false,
      parent_category_id: null,
      rank: 3,
      metadata: null,
      category_children: [
        {
          id: "pcat_01HE0TSXPRHT65MPJR0D15V1ZV",
          created_at: "2023-10-30T17:41:18.163Z",
          updated_at: "2024-07-16T11:07:18.505Z",
          name: "Necklaces ",
          description: "",
          handle: "Necklaces",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TBF57CC2CP81R4A48TEY8",
          rank: 0,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBMPEDYS39JWB9JZJ2H9GFT",
          created_at: "2023-11-28T18:57:35.158Z",
          updated_at: "2024-07-16T11:07:18.505Z",
          name: "Bracelets/Bangles",
          description: "",
          handle: "Bracelets-Bangles",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TBF57CC2CP81R4A48TEY8",
          rank: 1,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBMQDJXCF3HBTDWGK7D6YSZ",
          created_at: "2023-11-28T18:58:07.062Z",
          updated_at: "2024-07-16T11:07:18.505Z",
          name: "Earrings",
          description: "",
          handle: "Earrings",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TBF57CC2CP81R4A48TEY8",
          rank: 2,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBMRWMK0ECMAG2SYQ3BEJK8",
          created_at: "2023-11-28T18:58:55.244Z",
          updated_at: "2024-07-16T11:07:18.505Z",
          name: "Jewelry Set",
          description: "",
          handle: "Jewelry-set",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TBF57CC2CP81R4A48TEY8",
          rank: 3,
          metadata: null,
          category_children: [],
        },
      ],
      parent_category: null,
    },
    {
      id: "pcat_01HE0TCYRY8EJJC99KHP1X83VN",
      created_at: "2023-10-30T17:34:13.274Z",
      updated_at: "2023-11-30T06:57:53.751Z",
      name: "HOME FASHION",
      description: "",
      handle: "Homefashion",
      is_active: true,
      is_internal: false,
      parent_category_id: null,
      rank: 4,
      metadata: null,
      category_children: [
        {
          id: "pcat_01HE0TVPYT69MG90PQ8K2NZ0BJ",
          created_at: "2023-10-30T17:42:16.787Z",
          updated_at: "2023-11-30T06:57:53.751Z",
          name: "New Arrivals",
          description: "",
          handle: "new-arrivals",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TCYRY8EJJC99KHP1X83VN",
          rank: 0,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBN0T1W0KCSRHSB4J35FJ9W",
          created_at: "2023-11-28T19:03:14.741Z",
          updated_at: "2023-11-30T17:28:04.368Z",
          name: "Bath Towels",
          description: "",
          handle: "Bath-Towels",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TCYRY8EJJC99KHP1X83VN",
          rank: 1,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBN1GEAV1HEZ7SF3V3WETV2",
          created_at: "2023-11-28T19:03:37.668Z",
          updated_at: "2023-11-30T06:57:53.751Z",
          name: "Decor",
          description: "",
          handle: "Decor",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TCYRY8EJJC99KHP1X83VN",
          rank: 2,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBN242QRRAP3KR305FG1BKQ",
          created_at: "2023-11-28T19:03:57.777Z",
          updated_at: "2023-11-30T06:57:53.751Z",
          name: "Lighting",
          description: "",
          handle: "Lighting",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TCYRY8EJJC99KHP1X83VN",
          rank: 3,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBN2KQ4MBSTSYHP8G14T2V1",
          created_at: "2023-11-28T19:04:13.790Z",
          updated_at: "2024-01-04T17:47:55.648Z",
          name: "Tabletop and Tableware",
          description: "",
          handle: "Tabletop-and-Tableware",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TCYRY8EJJC99KHP1X83VN",
          rank: 4,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBN3CN8PM7M89KKAQAP47HP",
          created_at: "2023-11-28T19:04:39.330Z",
          updated_at: "2023-11-30T06:57:53.751Z",
          name: "Rugs & Bathmats",
          description: "",
          handle: "Rugs-Bathmats",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TCYRY8EJJC99KHP1X83VN",
          rank: 5,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBN4PGMTHRDYT2A0T0XZWWS",
          created_at: "2023-11-28T19:05:22.189Z",
          updated_at: "2023-11-30T06:57:53.751Z",
          name: "For Pets & Pet Lovers",
          description: "",
          handle: "for-pet-pet lovers",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TCYRY8EJJC99KHP1X83VN",
          rank: 6,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HKASF769CDMZJP9DHHT56AJF",
          created_at: "2024-01-04T17:48:52.281Z",
          updated_at: "2024-01-04T17:48:52.281Z",
          name: "Plant Decor and Garden",
          description: "",
          handle: "Plant-Decor-and-Garden",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TCYRY8EJJC99KHP1X83VN",
          rank: 7,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HP43CD9DRNPCVT7ESEG01P7Z",
          created_at: "2024-02-08T10:14:30.436Z",
          updated_at: "2024-02-08T10:14:30.436Z",
          name: "Cushion",
          description: "",
          handle: "cushion",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TCYRY8EJJC99KHP1X83VN",
          rank: 8,
          metadata: null,
          category_children: [],
        },
      ],
      parent_category: null,
    },
    {
      id: "pcat_01HE0TE49HY8WDRE7746ZNHGTB",
      created_at: "2023-10-30T17:34:51.693Z",
      updated_at: "2023-10-30T17:34:51.693Z",
      name: "FOOTWEAR",
      description: "",
      handle: "Footwear",
      is_active: true,
      is_internal: false,
      parent_category_id: null,
      rank: 5,
      metadata: null,
      category_children: [
        {
          id: "pcat_01HE0TXSP6SF0HQ6SVE1HY84RT",
          created_at: "2023-10-30T17:43:25.120Z",
          updated_at: "2023-11-28T19:11:32.782Z",
          name: "Shoes",
          description: "",
          handle: "Shoes",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TE49HY8WDRE7746ZNHGTB",
          rank: 0,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBNGRHSSNQM2DRD1H7PG9P0",
          created_at: "2023-11-28T19:11:57.490Z",
          updated_at: "2023-11-28T19:11:57.490Z",
          name: "Slippers",
          description: "",
          handle: "slippers",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TE49HY8WDRE7746ZNHGTB",
          rank: 1,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBNH9J6X05031FGA9ZGZN2Q",
          created_at: "2023-11-28T19:12:14.909Z",
          updated_at: "2023-11-28T19:12:14.909Z",
          name: "Sandles",
          description: "",
          handle: "Sandles",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TE49HY8WDRE7746ZNHGTB",
          rank: 2,
          metadata: null,
          category_children: [],
        },
        {
          id: "pcat_01HGBNKJ8X740CY856FS9MYHJT",
          created_at: "2023-11-28T19:13:29.358Z",
          updated_at: "2023-11-28T19:13:29.358Z",
          name: "Occasion Footwear",
          description: "",
          handle: "Occasion-Footwear",
          is_active: true,
          is_internal: false,
          parent_category_id: "pcat_01HE0TE49HY8WDRE7746ZNHGTB",
          rank: 3,
          metadata: null,
          category_children: [],
        },
      ],
      parent_category: null,
    },
  ];

  const insertCategories = async (parentId: string | null, data: (typeof categoryData)[number]) => {
    const [category] = await db
      .insert(CategoryTable)
      .values({
        title: data.name,
        slug: data.handle,
        updatedBy: session.user.id,
        parentCategoryId: parentId,
        description: data.description,
      })
      .returning();
    if (data.category_children.length > 0) {
      await Promise.all(data.category_children.map((child) => insertCategories(category.id, child as any)));
    }
  };
  await Promise.all(categoryData.map((category) => insertCategories(null, category)));
  return {
    categoriesCreated: insertCategories.length,
  };
};
