name: Test FTP Folder Access

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  test-ftp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Test FTP Folder Access
        run: |
          echo "open ${{ secrets.SSH_HOST }}" > ftp_commands.txt
          echo "user ${{ secrets.SSH_USERNAME }} ${{ secrets.SSH_PASSWORD }}" >> ftp_commands.txt
          echo "cd /SummitApp/UI" >> ftp_commands.txt
          echo "ls" >> ftp_commands.txt
          echo "quit" >> ftp_commands.txt
          ftp -n -v < ftp_commands.txt
